require('which-key').register({
  ['+'] = { 'Expand diff context' },
  ['-'] = { 'Shrink diff context' },
  ['0'] = { 'Reset diff context' },
  ['<'] = { 'Jump to previous hunk' },
  ['>'] = { 'Jump to next hunk' },
  ['?'] = { 'Toggle Magit help' },
  DDD = 'which_key_ignore',
  C = {
    name = 'Magit',
    A = { 'Amend last commit' },
    C = { 'Commit staged changes' },
    F = { 'Fixup last commit' },
    U = { 'Leave commit mode' },
  },
  E = { 'Edit current item' },
  F = { 'Stage/unstage current file' },
  I = { 'Add current file to .gitignore' },
  L = { 'Stage/unstage current line' },
  M = { 'Mark current line for staging', mode = { 'n', 'v' } },
  R = { 'Refresh Magit buffer' },
  S = { 'Stage/unstage current item', mode = { 'n', 'v' } },
  q = { 'Close Magit buffer' },
}, { buffer = 0 })
