require('which-key').add({
  buffer = 0,
  {
    { '+', desc = 'Expand diff context' },
    { '-', desc = 'Shrink diff context' },
    { '0', desc = 'Reset diff context' },
    { '<', desc = 'Jump to previous hunk' },
    { '>', desc = 'Jump to next hunk' },
    { '?', desc = 'Toggle Magit help' },
    -- TODO: Not clear whether this is still needed
    -- { 'DDD', desc = 'which_key_ignore', },
    { 'C', group = 'Magit' },
    { 'CA', desc = 'Amend last commit' },
    { 'CC', desc = 'Commit staged changes' },
    { 'CF', desc = 'Fixup last commit' },
    { 'CU', desc = 'Leave commit mode' },
    { 'E', desc = 'Edit current item' },
    { 'F', desc = 'Stage/unstage current file' },
    { 'I', desc = 'Add current file to .gitignore' },
    { 'L', desc = 'Stage/unstage current line' },
    { 'M', desc = 'Mark current line for staging', mode = { 'n', 'v' } },
    { 'R', desc = 'Refresh Magit buffer' },
    { 'S', desc = 'Stage/unstage current item', mode = { 'n', 'v' } },
    { 'q', desc = 'Close Magit buffer' },
  },
})
