# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  theme:
    cherryPickedCommitFgColor:
      - "#57a5e5"
    cherryPickedCommitBgColor:
      - "#de5d68"
    activeBorderColor:
      - "#de5d68"
      - "bold"
    unstagedChangesColor:
      - "#de5d68"
    selectedLineBgColor:
      - "#37383d"
    searchingActiveBorderColor:
      - "#de5d68"
      - "bold"
    optionsTextColor:
      - "#57a5e5"
    inactiveBorderColor:
      - "#5a5b5e"
    defaultFgColor:
      - "#a7aab0"
  nerdFontsVersion: "3"
git:
  autoFetch: false
  autoForwardBranches: none
  overrideGpg: true # we use gpg-agent, so this can be enabled to allow commit rewording
os:
  editPreset: "nvim-remote"
  copyToClipboardCmd: printf {{text}} | xsel --clipboard --input
