#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
show_hidden = true
linemode = "size"

[plugin]
prepend_spotters = [
  { mime = "audio/mpegurl", run = "code" },  # ignore .m3u files
  { mime = "audio/*", run = "spot-audio" },
  { mime = "image/*", run = "spot-image" },
  { mime = "video/*", run = "spot-video" },
]
