# Configuration parameter reference: https://clangd.llvm.org/config
InlayHints:
  DefaultArguments: true
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add:
      - boost-*
      - bugprone-*
      - clang-analyzer-*
      - cppcoreguidelines-*
      - misc-*
      - modernize-*
      - performance-*
      - readability-*
    Remove:
      - bugprone-easily-swappable-parameters
      - bugprone-unchecked-optional-access # too many false positives, may re-enable if the rules are improved in the future
      - cppcoreguidelines-pro-bounds-array-to-pointer-decay # too much noise because ROS logging macros decay arrays to pointers
      - cppcoreguidelines-pro-type-union-access # too much noise because PCL uses unions in point types
      - cppcoreguidelines-pro-type-vararg # too much noise because ROS logging macros use vararg
      - modernize-return-braced-init-list
      - modernize-use-nodiscard
      - modernize-use-trailing-return-type
      - readability-braces-around-statements
      - readability-uppercase-literal-suffix # because all my code has lowercase literal suffixes
      - readability-math-missing-parentheses # suggests useless parentheses
    CheckOptions:
      cppcoreguidelines-special-member-functions.AllowSoleDefaultDtor: true
      misc-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic: true
      readability-function-cognitive-complexity.DescribeBasicIncrements: false # too much noise
      readability-function-cognitive-complexity.IgnoreMacros: true
      readability-identifier-length.IgnoredLoopCounterNames: "^[ijk_xyz]$"
      readability-identifier-length.IgnoredParameterNames: "^[xyz]$"
      readability-identifier-length.IgnoredVariableNames: "^[Rxyz]$"
      readability-identifier-length.MinimumParameterNameLength: 2
      readability-identifier-length.MinimumVariableNameLength: 2
---
# Relax rules for unit and accuracy tests
If:
  PathMatch: ".*tests?/.*_test.cpp"
Diagnostics:
  ClangTidy:
    Remove:
      - cppcoreguidelines-avoid-goto # triggers on EXPECT_THROW
      - cppcoreguidelines-avoid-magic-numbers # its okay to have various unnamed numbers in test cases
      - cppcoreguidelines-avoid-non-const-global-variables
      - cppcoreguidelines-owning-memory # triggers on TEST and TEST_F
      - cppcoreguidelines-special-member-functions # triggers on TEST and TEST_F
      - readability-function-cognitive-complexity
      - readability-magic-numbers # its okay to have various unnamed numbers in test cases
